<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-17T12:23:51 IST" name="Suite" finished-at="2023-08-17T12:26:47 IST" duration-ms="176111">
    <groups>
      <group name="ErrorValidations">
        <method signature="ErrorValidationsTest.ProductValidation()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" name="ProductValidation" class="Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest"/>
        <method signature="ErrorValidationsTest.loginErrorValidation()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" name="loginErrorValidation" class="Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest"/>
      </group> <!-- ErrorValidations -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" name="submitOrder" class="Automation.SeleniumrepeatProject.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-08-17T12:23:51 IST" name="Submit Order Test" finished-at="2023-08-17T12:25:46 IST" duration-ms="114801">
      <class name="Automation.SeleniumrepeatProject.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:23:52 IST" name="launchApplication" finished-at="2023-08-17T12:24:37 IST" duration-ms="44457" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:24:37 IST" name="submitOrder" data-provider="getData" finished-at="2023-08-17T12:25:00 IST" duration-ms="23570" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Mkyasv@1234, ProductName=ZARA COAT 3, CountryName=india, username=shreyasdoshi48@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:25:00 IST" name="TearDown" finished-at="2023-08-17T12:25:06 IST" duration-ms="5855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:25:06 IST" name="launchApplication" finished-at="2023-08-17T12:25:19 IST" duration-ms="12587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:25:19 IST" name="submitOrder" data-provider="getData" finished-at="2023-08-17T12:25:24 IST" duration-ms="4790" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Ssd@12345, ProductName=ADIDAS ORIGINAL, CountryName=aus, username=sswarali05@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:25:24 IST" name="TearDown" finished-at="2023-08-17T12:25:29 IST" duration-ms="4968" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:25:29 IST" name="launchApplication" finished-at="2023-08-17T12:25:41 IST" duration-ms="12622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OderDisplay()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:25:41 IST" name="OderDisplay" finished-at="2023-08-17T12:25:42 IST" depends-on-methods="Automation.SeleniumrepeatProject.Tests.SubmitOrderTest.submitOrder" duration-ms="1031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OderDisplay -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.SubmitOrderTest@42b02722]" started-at="2023-08-17T12:25:42 IST" name="TearDown" finished-at="2023-08-17T12:25:46 IST" duration-ms="3670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- Automation.SeleniumrepeatProject.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2023-08-17T12:25:47 IST" name="Error Valications Test" finished-at="2023-08-17T12:26:47 IST" duration-ms="60433">
      <class name="Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:25:47 IST" name="launchApplication" finished-at="2023-08-17T12:25:58 IST" duration-ms="11428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductValidation()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:25:58 IST" name="ProductValidation" finished-at="2023-08-17T12:26:12 IST" duration-ms="13873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductValidation -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:26:12 IST" name="TearDown" finished-at="2023-08-17T12:26:14 IST" duration-ms="2058" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:26:14 IST" name="launchApplication" finished-at="2023-08-17T12:26:26 IST" duration-ms="12152" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:26:26 IST" name="loginErrorValidation" finished-at="2023-08-17T12:26:27 IST" duration-ms="591" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorret email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorret email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest.loginErrorValidation(ErrorValidationsTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:26:27 IST" name="TearDown" finished-at="2023-08-17T12:26:31 IST" duration-ms="3529" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:26:31 IST" name="launchApplication" finished-at="2023-08-17T12:26:43 IST" duration-ms="12408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:26:43 IST" name="loginErrorValidation" finished-at="2023-08-17T12:26:44 IST" duration-ms="565" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorret email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorret email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest.loginErrorValidation(ErrorValidationsTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest@7ac0e420]" started-at="2023-08-17T12:26:44 IST" name="TearDown" finished-at="2023-08-17T12:26:47 IST" duration-ms="3287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- Automation.SeleniumrepeatProject.Tests.ErrorValidationsTest -->
    </test> <!-- Error Valications Test -->
  </suite> <!-- Suite -->
</testng-results>
